// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ_ikfi3MK4WUnHk1xC_eGD0qF9LJTq4U',
    appId: '1:13536880310:web:3c1f4e6940b600c9cae817',
    messagingSenderId: '13536880310',
    projectId: 'ginrai-9200f',
    authDomain: 'ginrai-9200f.firebaseapp.com',
    databaseURL: 'https://ginrai-9200f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginrai-9200f.appspot.com',
    measurementId: 'G-HXWCVZFF3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbbZtiqhyxJoci50PF-EZYVip1JjsNRX4',
    appId: '1:13536880310:android:db6c091133fc33dccae817',
    messagingSenderId: '13536880310',
    projectId: 'ginrai-9200f',
    databaseURL: 'https://ginrai-9200f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginrai-9200f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmJBMosm6Rf-wY09iGqptkgXaJ1Z0nAvE',
    appId: '1:13536880310:ios:5f79b0aa4e936073cae817',
    messagingSenderId: '13536880310',
    projectId: 'ginrai-9200f',
    databaseURL: 'https://ginrai-9200f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginrai-9200f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRandomfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmJBMosm6Rf-wY09iGqptkgXaJ1Z0nAvE',
    appId: '1:13536880310:ios:5f79b0aa4e936073cae817',
    messagingSenderId: '13536880310',
    projectId: 'ginrai-9200f',
    databaseURL: 'https://ginrai-9200f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginrai-9200f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRandomfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ_ikfi3MK4WUnHk1xC_eGD0qF9LJTq4U',
    appId: '1:13536880310:web:a1691b1c168fa5fccae817',
    messagingSenderId: '13536880310',
    projectId: 'ginrai-9200f',
    authDomain: 'ginrai-9200f.firebaseapp.com',
    databaseURL: 'https://ginrai-9200f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginrai-9200f.appspot.com',
    measurementId: 'G-C6XDLXWGTE',
  );
}
